
SYMBOL_YFINANCE_INDEX = 0
SYMBOL_XTB_INDEX = 1
SYMBOL_INVESTING_INDEX = 2

SYMBOL_TO_X = {
    "BTCUSD":   ["BTC-USD", "BITCOIN", "BTCUSD"],
    "GOLD":     ["GC=F", "GOLD", "GOLD"],
    "EURUSD":   ["EURUSD=X", "EURUSD", "EURUSD"]
}
