
SYMBOL_XTB_INDEX = 0
SYMBOL_INVESTING_INDEX = 1

SYMBOL_TO_X = {
    "BITCOIN":   ["BITCOIN", "BTCUSD"],
    "BTCUSD":  ["BITCOIN", "BTCUSD"],
    "GOLD":     ["GOLD", "GOLD"],
    "EURUSD":   ["EURUSD", "EURUSD"]
}
