from enum import Enum
import itertools

REGIONS = {
    "ar": "Argentina",
    "at": "Austria",
    "au": "Australia",
    "be": "Belgium",
    "br": "Brazil",
    "ca": "Canada",
    "ch": "Switzerland",
    "cl": "Chile",
    "cn": "China",
    "co": "Colombia",
    "cz": "Czechia",
    "de": "Germany",
    "dk": "Denmark",
    "ee": "Estonia",
    "eg": "Egypt",
    "es": "Spain",
    "fi": "Finland",
    "fr": "France",
    "gb": "United Kingdom",
    "gr": "Greece",
    "hk": "Hong Kong",
    "hu": "Hungary",
    "id": "Indonesia",
    "ie": "Ireland",
    "il": "Israel",
    "in": "India",
    "is": "Iceland",
    "it": "Italy",
    "jp": "Japan",
    "kr": "South Korea",
    "kw": "Kuwait",
    "lk": "Sri Lanka",
    "lt": "Lithuania",
    "lv": "Latvia",
    "mx": "Mexico",
    "my": "Malaysia",
    "nl": "Netherlands",
    "no": "Norway",
    "nz": "New Zealand",
    "pe": "Peru",
    "ph": "Philippines",
    "pk": "Pakistan",
    "pl": "Poland",
    "pt": "Portugal",
    "qa": "Qatar",
    "ro": "Romania",
    "ru": "Russia",
    "sa": "Saudi Arabia",
    "se": "Sweden",
    "sg": "Singapore",
    "sr": "Suriname",
    "sw": "Switzerland",
    "th": "Thailand",
    "tr": "Türkiye",
    "tw": "Taiwan",
    "us": "United States",
    "ve": "Venezuela",
    "vn": "Vietnam",
    "za": "South Africa",
}

EXCHANGES = {
    "ar": ["BUE"],
    "at": ["VIE"],
    "au": ["ASX"],
    "be": ["BRU"],
    "br": ["SAO"],
    "ca": ["CNQ", "NEO", "TOR", "VAN"],
    "ch": ["EBS"],
    "cl": ["SGO"],
    "cn": ["SHH", "SHZ"],
    "co": ["BVC"],
    "cz": ["PRA"],
    "de": ["BER", "DUS", "FRA", "GER", "HAM", "MUN", "STU"],
    "dk": ["CPH"],
    "ee": ["TAL"],
    "eg": ["CAI"],
    "es": ["MCE"],
    "fi": ["HEL"],
    "fr": ["PAR"],
    "gb": ["AQS", "IOB", "LSE"],
    "gr": ["ATH"],
    "hk": ["HKG"],
    "hu": ["BUD"],
    "id": ["JKT"],
    "ie": ["ISE"],
    "il": ["TLV"],
    "in": ["BSE", "NSI"],
    "is": ["ICE"],
    "it": ["MIL"],
    "jp": ["FKA", "JPX", "SAP"],
    "kr": ["KOE", "KSC"],
    "kw": ["KUW"],
    "lk": [],
    "lt": ["LIT"],
    "lv": ["RIS"],
    "mx": ["MEX"],
    "my": ["KLS"],
    "nl": ["AMS"],
    "no": ["OSL"],
    "nz": ["NZE"],
    "pe": [],
    "ph": ["PHP", "PHS"],
    "pk": [],
    "pl": ["WSE"],
    "pt": ["LIS"],
    "qa": ["DOH"],
    "ro": ["BVB"],
    "ru": [],
    "sa": ["SAU"],
    "se": ["STO"],
    "sg": ["SES"],
    "sr": [],
    "sw": ["EBS"],
    "th": ["SET"],
    "tr": ["IST"],
    "tw": ["TAI", "TWO"],
    "us": [
        "ASE",
        "BTS",
        "CXI",
        "NCM",
        "NGM",
        "NMS",
        "NYQ",
        "OEM",
        "OQB",
        "OQX",
        "PCX",
        "PNK",
        "YHD",
    ],
    "ve": ["CCS"],
    "vn": [],
    "za": ["JNB"],
}

ALL_EXCHANGES = list(itertools.chain.from_iterable(EXCHANGES.values()))


class SECTOR(Enum):
    BASIC_MATERIALS = "Basic Materials"
    COMMUNICATION_SERVICES = "Communication Services"
    CONSUMER_CYCLICAL = "Consumer Cyclical"
    CONSUMER_DEFENSIVE = "Consumer Defensive"
    ENERGY = "Energy"
    FINANCIAL_SERVICES = "Financial Services"
    HEALTHCARE = "Healthcare"
    INDUSTRIALS = "Industrials"
    REAL_ESTATE = "Real Estate"
    TECHNOLOGY = "Technology"
    UTILITIES = "Utilities"

class INDUSTRY(str, Enum):
    BASIC_MATERIALS = "Basic Materials"
    COMMUNICATION_SERVICES = "Communication Services"
    CONSUMER_CYCLICAL = "Consumer Cyclical"
    CONSUMER_DEFENSIVE = "Consumer Defensive"
    ENERGY = "Energy"
    FINANCIAL_SERVICES = "Financial Services"
    HEALTHCARE = "Healthcare"
    INDUSTRIALS = "Industrials"
    REAL_ESTATE = "Real Estate"
    TECHNOLOGY = "Technology"
    UTILITIES = "Utilities"

SECTORS = {
  INDUSTRY.BASIC_MATERIALS: [
    "Agricultural Inputs",
    "Aluminum",
    "Building Materials",
    "Chemicals",
    "Coking Coal",
    "Copper",
    "Gold",
    "Lumber & Wood Production",
    "Other Industrial Metals & Mining",
    "Other Precious Metals & Mining",
    "Paper & Paper Products",
    "Silver",
    "Specialty Chemicals",
    "Steel"
  ],
  INDUSTRY.COMMUNICATION_SERVICES: [
    "Advertising Agencies",
    "Broadcasting",
    "Electronic Gaming & Multimedia",
    "Entertainment",
    "Internet Content & Information",
    "Publishing",
    "Telecom Services"
  ],
  INDUSTRY.CONSUMER_CYCLICAL: [
    "Apparel Manufacturing",
    "Apparel Retail",
    "Auto & Truck Dealerships",
    "Auto Manufacturers",
    "Auto Parts",
    "Department Stores",
    "Footwear & Accessories",
    "Furnishings, Fixtures & Appliances",
    "Gambling",
    "Home Improvement Retail",
    "Internet Retail",
    "Leisure",
    "Lodging",
    "Luxury Goods",
    "Packaging & Containers",
    "Personal Services",
    "Recreational Vehicles",
    "Residential Construction",
    "Resorts & Casinos",
    "Restaurants",
    "Specialty Retail",
    "Textile Manufacturing",
    "Travel Services"
  ],
  INDUSTRY.CONSUMER_DEFENSIVE: [
    "Beverages - Brewers",
    "Beverages - Non-Alcoholic",
    "Beverages - Wineries & Distilleries",
    "Confectioners",
    "Discount Stores",
    "Education & Training Services",
    "Farm Products",
    "Food Distribution",
    "Grocery Stores",
    "Household & Personal Products",
    "Packaged Foods",
    "Tobacco"
  ],
  INDUSTRY.ENERGY: [
    "Oil Gas Drilling",
    "Oil Gas E P",
    "Oil Gas Equipment Services",
    "Oil Gas Integrated",
    "Oil Gas Midstream",
    "Oil Gas Refining Marketing",
    "Thermal Coal",
    "Uranium"
  ],
  INDUSTRY.FINANCIAL_SERVICES: [
    "Asset Management",
    "Banks Diversified",
    "Banks Regional",
    "Capital Markets",
    "Credit Services",
    "Financial Conglomerates",
    "Financial Data Stock Exchanges",
    "Insurance Brokers",
    "Insurance Diversified",
    "Insurance Life",
    "Insurance Property Casualty",
    "Insurance Reinsurance",
    "Insurance Specialty",
    "Mortgage Finance",
    "Shell Companies"
  ],
  INDUSTRY.HEALTHCARE: [
    "Biotechnology",
    "Diagnostics Research",
    "Drug Manufacturers General",
    "Drug Manufacturers Specialty Generic",
    "Health Information Services",
    "Healthcare Plans",
    "Medical Care Facilities",
    "Medical Devices",
    "Medical Distribution",
    "Medical Instruments Supplies",
    "Pharmaceutical Retailers"
  ],
  INDUSTRY.INDUSTRIALS: [
    "Aerospace Defense",
    "Airlines",
    "Airports Air Services",
    "Building Products Equipment",
    "Business Equipment Supplies",
    "Conglomerates",
    "Consulting Services",
    "Electrical Equipment Parts",
    "Engineering Construction",
    "Farm Heavy Construction Machinery",
    "Industrial Distribution",
    "Infrastructure Operations",
    "Integrated Freight Logistics",
    "Marine Shipping",
    "Metal Fabrication",
    "Pollution Treatment Controls",
    "Railroads",
    "Rental Leasing Services",
    "Security Protection Services",
    "Specialty Business Services",
    "Specialty Industrial Machinery",
    "Staffing Employment Services",
    "Tools Accessories",
    "Trucking",
    "Waste Management"
  ],
  INDUSTRY.REAL_ESTATE: [
    "Real Estate Development",
    "Real Estate Diversified",
    "Real Estate Services",
    "Reit Diversified",
    "Reit Healthcare Facilities",
    "Reit Hotel Motel",
    "Reit Industrial",
    "Reit Mortgage",
    "Reit Office",
    "Reit Residential",
    "Reit Retail",
    "Reit Specialty"
  ],
  INDUSTRY.TECHNOLOGY: [
    "Communication Equipment",
    "Computer Hardware",
    "Consumer Electronics",
    "Electronic Components",
    "Electronics Computer Distribution",
    "Information Technology Services",
    "Scientific Technical Instruments",
    "Semiconductor Equipment Materials",
    "Semiconductors",
    "Software Application",
    "Software Infrastructure",
    "Solar"
  ],
  INDUSTRY.UTILITIES: [
    "Utilities Diversified",
    "Utilities Independent Power Producers",
    "Utilities Regulated Electric",
    "Utilities Regulated Gas",
    "Utilities Regulated Water",
    "Utilities Renewable"
  ]
}
